### ISSUE TITLE
Module parse failed: Unexpected token (10:22)

### ISSUE THREAD

**Issue by codexJoin** [WJSoftware/wj-config#19]
Failed to compile. - React 17.0

./node_modules/wj-config/Environment.js 10:22
Module parse failed: Unexpected token (10:22)
File was processed with these loaders:
 * ./node_modules/babel-loader/lib/index.js
You may need an additional loader to handle the result of these loaders.
|    * Default list of environment names.
|    */
>   static defaultNames = ['Development', 'PreProduction', 'Production'];
|   value;
|   names;

**Comment by webJose** [comment]
Hi.  React 17.  Using Create React App?  I haven't tested it.  Which version are you trying?  I released Release Candidate 0 earlier today.

**Comment by webJose** [comment]
Hey no problem.  I am glad you were able to resolve this.  If you have the time, I'll appreciate a quick explanation on how you resolved it.  Not for me, but for others that might come visit this issue in search for help.

In any case, enjoy the package.  I worked hard to make the best configuration package for JavaScript.  Hopefully it is.
